#!/usr/bin/env bash

if test $(echo "${2}") ; then
   youtube_url="${2}"
   download_path="${1}"
else
   youtube_url="${1}"
   download_path="$(pwd)"
fi

yt-dlp --rm-cache-dir
youtube-dl --rm-cache-dir

cd download_path
youtube-dl --rm-cache-dir
while true; do
  youtube-dl --no-warnings --ignore-config --ignore-errors --audio-format mp3 --audio-quality 7 --retries 40 --no-part --age-limit 16  --no-cache-dir --download-archive the_list.txt --continue --yes-playlist -x "${@}" && break
done
