#!/usr/bin/env bash

if test $(echo "${2}") ; then
   youtube_url="${2}"
   download_path="${1}"
else
   youtube_url="${1}"
   download_path="$(pwd)"
fi

yt-dlp --rm-cache-dir
youtube-dl --rm-cache-dir

cd download_path
while true; do
  youtube-dl --no-warnings --ignore-config --ignore-errors -f 'bestvideo[height=480][ext=mp4]+bestaudio[ext=m4a]' --audio-format mp3 --audio-quality 7 --retries 40 --no-cache-dir "aria2c" --external-downloader-args "-c -x 16 --timeout 8 --retry-wait 3 --file-allocation=none --allow-overwrite=false" -w --batch-file="${@}" && break
done
cd -
