#!/usr/bin/env bash

yt-dlp -i -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/mp4" --recode-video mp4 --all-subs --no-cache-dir -x "${@}"
#-f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4' --recode-video mp4
if test $(echo "${2}") ; then
   youtube_url="${2}"
   download_path="${1}"
else
   youtube_url="${1}"
   download_path="$(pwd)"
fi

yt-dlp --rm-cache-dir
youtube-dl --rm-cache-dir

cd "$download_path"
youtube-dl --no-warnings --ignore-config --ignore-errors -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --all-subs --no-cache-dir --retries 40 --no-playlist -w --external-downloader "aria2c" --external-downloader-args "-c -x 16 --timeout 8 --retry-wait 3 --file-allocation=none --allow-overwrite=false" -x "$youtube_url"
cd -
