#!/usr/bin/env bash

if test $(echo "${2}") ; then
   youtube_url="${2}"
   download_path="${1}"
else
   youtube_url="${1}"
   download_path="$(pwd)"
fi

yt-dlp --rm-cache-dir
youtube-dl --rm-cache-dir
basedir=$(dirname $1)
if ! ls $basedir/cookie_content.txt &> /dev/null ; then
  python $basedir/get-session-cookie.py | awk '$1=$1' FS="': '" OFS=":" | awk  -F "'" '{print  $2 $3 $4 $5 $6}' | sed 's/, / --add-header /g' > $basedir/cookie_content.txt
fi

cd download_path
youtube-dl --rm-cache-dir
while true; do
  youtube-dl --no-warnings --ignore-config --ignore-errors --audio-format mp3 --audio-quality 7 --retries 40 --no-part --age-limit 16 --add-header $(cat $basedir/cookie_content.txt) --no-cache-dir --continue --yes-playlist -x "${@}" && break
done
