#!/usr/bin/env bash

basedir=$(dirname $@)
if ! ls $basedir/cookie_content.txt &> /dev/null ; then
  python $basedir/get-session-cookie.py | awk '$1=$1' FS="': '" OFS=":" | awk  -F "'" '{print  $2 $3 $4 $5 $6}' | sed 's/, / --add-header /g' > $basedir/cookie_content.txt
fi

yt-dlp --rm-cache-dir
youtube-dl --rm-cache-dir

cd download_path
while true; do
  youtube-dl --no-warnings --ignore-config --ignore-errors --audio-format mp3 --retries 40 --no-part --age-limit 16 --add-header $(cat $basedir/cookie_content.txt) --no-cache-dir --continue --batch-file="${@}" && break
done
