#!/usr/bin/bash

if test $(echo "${2}") ; then
   youtube_url="${2}"
   download_path="${1}"
else
   youtube_url="${1}"
   download_path="$(pwd)"
fi

echo $youtube_url
echo $download_path

cd "$download_path"
if ! test $(echo "$youtube_url" | grep -E "&list="); then
  echo "Error - Link doesn't contain a Youtube Playlist!"
  exit
fi

yt-dlp --rm-cache-dir
youtube-dl --rm-cache-dir

cd "$download_path"
while true; do
   yt-dlp --no-warnings --ignore-config --ignore-errors --all-subs --no-cache-dir --retries 40 $(yt-dlp --flat-playlist --print url "$youtube_url") --download-archive the_list.txt -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best' && break
done
