#!/usr/bin/bash

if test $(echo "${2}") ; then
   youtube_url="${2}"
   download_path="${1}"
else
   youtube_url="${1}"
   download_path="$(pwd)"
fi

echo $youtube_url
echo $download_path

cd "$download_path"
if ! test $(echo "$youtube_url" | grep -E "&list="); then
  echo "Error - Link doesn't contain a Youtube Playlist!"
  exit
fi

yt-dlp --rm-cache-dir
youtube-dl --rm-cache-dir

cd "$download_path"
youtube-dl --external-downloader "aria2c" --external-downloader-args "-c -x 16 --timeout 8 --retry-wait 3 --file-allocation=none --allow-overwrite=false" --no-warnings --ignore-config --ignore-errors -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --all-subs --no-cache-dir --retries 40 --yes-playlist -w -x "$youtube_url" 
cd -
